/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({ 'exteriorWashing' : IDL.Null });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'alt' : IDL.Opt(IDL.Text),
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
});
export const InquiryStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'archived' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Int,
  'service' : ServiceType,
  'status' : InquiryStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const GalleryImageMetadata = IDL.Record({
  'id' : IDL.Text,
  'alt' : IDL.Opt(IDL.Text),
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        ServiceType,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Int],
      [],
    ),
  'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryImage' : IDL.Func([IDL.Text], [IDL.Opt(GalleryImage)], ['query']),
  'getInquiry' : IDL.Func([IDL.Int], [Inquiry], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listGalleryImages' : IDL.Func(
      [],
      [IDL.Vec(GalleryImageMetadata)],
      ['query'],
    ),
  'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({ 'exteriorWashing' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'alt' : IDL.Opt(IDL.Text),
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
  });
  const InquiryStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Int,
    'service' : ServiceType,
    'status' : InquiryStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const GalleryImageMetadata = IDL.Record({
    'id' : IDL.Text,
    'alt' : IDL.Opt(IDL.Text),
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          ServiceType,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Int],
        [],
      ),
    'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryImage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GalleryImage)],
        ['query'],
      ),
    'getInquiry' : IDL.Func([IDL.Int], [Inquiry], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listGalleryImages' : IDL.Func(
        [],
        [IDL.Vec(GalleryImageMetadata)],
        ['query'],
      ),
    'listInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };